### ISSUE TITLE
Jetbrains 系列授权(支持 2018.1.x 版本) | 沉默着欢喜

### ISSUE THREAD

**Issue by LatteCat** [LatteCat/LatteCat.github.io#1]
https://blog.dearlattecat.com/posts/44065/

**Comment by urzz** [comment]
感谢博主
idea 实测可用
有个小问题，Linux下jar包生成的key文件需要放到对应路径下的config目录中，所以最终选择的路径应该是<PRODUCT><VERSION>/config

**Comment by SNY7** [comment]
怪了，mac 下 webstorm 可用，但 idea 不可用，版本是2018.1.6

**Comment by urzz** [comment]
@SNY7 idea 版本回退到2018.1.5可以用，我今天升了2018.1.6也不能激活了。。我是linux

**Comment by SNY7** [comment]
@urzz 果然回退了是可以的，这种方式被封锁的可能性还是蛮高的感觉

**Comment by SNY7** [comment]
不折腾了……去买正版了……用了快10年了说不过去

**Comment by jf61975** [comment]
特意注册登录感谢博主啊~~
亲测phpstorm2018.1.6可用~
非常感谢~~

**Comment by LatteCat** [comment]
@jf61975 上面的人不是说不能激活 2018.1.6 么？最近 R 大已经更新了破解补丁，我试了下 Ideal Intellij 2018.2 可以破解成功，过段时间我再更新下文章和脚本

**Comment by Owen-Yu** [comment]
催更

**Comment by youyinnn** [comment]
你这和R大的JetbrainsCrack没有任何关系吧？有点迷啊

**Comment by youyinnn** [comment]
我咋感觉生成key更麻烦了- - 我用了R大的JetbrainsCrack2.10 java -jar一下 按照步骤来就好了 挺方便的

**Comment by LatteCat** [comment]
@youyinnn 你说的 JetbrainsCrack2.10 是最新的脚本，我还没把教程更新到最新的脚本，我在上一条评论中说的“封装了一层”是指 JetbrainsCrack2.9 的破解，感谢 R 大！
